language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -e . --use-mirrors

script:
  - python -m compileall
  - py.test --cov-report term-missing --cov csp csp

after-success:
  - coveralls

