language: python

python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"

install:
  - pip install -e . --use-mirrors

before-script:
  - pip install -r requirements.txt --use-mirrors

script: 
  - py.test --cov-report term-missing --cov csp csp

after-success:
  - coveralls

